spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    host: localhost
    port: 5432   # ✅ Add this line
    username: postgres
    password: Test@123
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/marketplugtest
    hikari:
      maximum-pool-size: 2

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    oauth2:
      authorization-server:
        issuer: http://auth-service
