server:
  port: 9001

spring:
  datasource:
    host: localhost
    password: Test@123
    username: postgres
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/marketplugtest
    port: 5432
    hikari: 
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service
          jwk-set-uri: http://auth-service/oauth2/jwks
