server:
  base-url: http://localhost:8081/user
  
spring:
  flyway:
    enabled: false
    table: flyway_schema_history_auth
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    host: localhost
    port: 5432   # ✅ Add this line
    username: postgres
    password: Test@123
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/marketplugtest
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

security:
  jwt:
    secret: ofz8Tz+1GJEJ5efPxvqkTACLqdIGUoreFguLAixE/KI=
  
logging:
  level:
    org.flywaydb.core: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security: DEBUG
